// WV Roofing — private object storage.
//
// Production: a private Vercel Blob store (London). Every read needs
// authentication; customers never receive storage links (images are streamed
// through the WV function), and the operator only gets short-lived presigned
// GET links for downloads.
// Test environment only (WVR_ENV=test): a local-folder driver with the same
// interface, so tests and the dev server run without a Blob store.
//
// Paths are always generated by the server:
//   projects/<projectId>/{incoming,originals,working,renders,evidence}/<uuid>.<ext>
"use strict";

const fs = require("fs");
const os = require("os");
const path = require("path");
const { HttpError } = require("./core.js");
const { isTest } = require("./capabilities.js");

const SAFE_PATH = /^[a-z0-9][a-z0-9/_.-]{0,254}$/;

/** @param {string} p */
function checkPath(p) {
  if (typeof p !== "string" || !SAFE_PATH.test(p) || p.includes("..") || p.includes("//")) {
    throw new HttpError(500, "server_error", "Invalid storage path.");
  }
  return p;
}

/** @param {Record<string, string | undefined>} env */
function configured(env) {
  return !!(env.BLOB_STORE_ID || env.BLOB_READ_WRITE_TOKEN) || isTest(env);
}

/**
 * @typedef {object} StoredObject
 * @property {ReadableStream<Uint8Array> | NodeJS.ReadableStream} stream
 * @property {string} contentType
 * @property {number} size
 */
/**
 * @typedef {object} StorageDriver
 * @property {"blob" | "fs"} kind
 * @property {(pathname: string, body: Buffer, contentType: string) => Promise<void>} put
 * @property {(pathname: string) => Promise<StoredObject | null>} get
 * @property {(pathname: string) => Promise<Buffer | null>} getBuffer
 * @property {(pathnames: string[]) => Promise<void>} del
 * @property {(prefix: string) => Promise<string[]>} list
 * @property {(pathname: string, opts: { contentTypes: string[], maxBytes: number, ttlSeconds: number }) => Promise<string>} presignPut
 * @property {(pathname: string, ttlSeconds: number) => Promise<string>} presignGet
 */

/** @returns {StorageDriver} */
function blobDriver() {
  const blob = require("@vercel/blob");
  /** @param {ReadableStream<Uint8Array>} stream */
  async function toBuffer(stream) {
    const chunks = [];
    const reader = stream.getReader();
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      chunks.push(Buffer.from(value));
    }
    return Buffer.concat(chunks);
  }
  return {
    kind: "blob",
    async put(pathname, body, contentType) {
      await blob.put(checkPath(pathname), body, { access: "private", contentType, addRandomSuffix: false, allowOverwrite: false });
    },
    async get(pathname) {
      const r = await blob.get(checkPath(pathname), { access: "private" });
      if (!r || r.statusCode !== 200) return null;
      return { stream: r.stream, contentType: r.blob.contentType, size: r.blob.size };
    },
    async getBuffer(pathname) {
      const r = await blob.get(checkPath(pathname), { access: "private" });
      if (!r || r.statusCode !== 200) return null;
      return toBuffer(r.stream);
    },
    async del(pathnames) {
      const list = pathnames.map(checkPath);
      if (list.length) await blob.del(list);
    },
    async list(prefix) {
      /** @type {string[]} */
      const out = [];
      /** @type {string | undefined} */
      let cursor;
      do {
        const page = await blob.list({ prefix: checkPath(prefix), cursor, limit: 1000 });
        for (const b of page.blobs) out.push(b.pathname);
        cursor = page.hasMore ? page.cursor : undefined;
      } while (cursor);
      return out;
    },
    async presignPut(pathname, opts) {
      const p = checkPath(pathname);
      const validUntil = Date.now() + opts.ttlSeconds * 1000;
      const token = await blob.issueSignedToken({
        pathname: p,
        operations: ["put"],
        validUntil,
        allowedContentTypes: opts.contentTypes,
        maximumSizeInBytes: opts.maxBytes,
      });
      const { presignedUrl } = await blob.presignUrl(token, {
        operation: "put",
        pathname: p,
        access: "private",
        validUntil,
        allowedContentTypes: opts.contentTypes,
        maximumSizeInBytes: opts.maxBytes,
        addRandomSuffix: false,
        allowOverwrite: false,
      });
      return presignedUrl;
    },
    async presignGet(pathname, ttlSeconds) {
      const p = checkPath(pathname);
      const validUntil = Date.now() + ttlSeconds * 1000;
      const token = await blob.issueSignedToken({ pathname: p, operations: ["get"], validUntil });
      const { presignedUrl } = await blob.presignUrl(token, { operation: "get", pathname: p, access: "private", validUntil });
      return presignedUrl;
    },
  };
}

/**
 * Local-folder driver (test environment only). Presigned URLs point at the dev
 * server's /__dev/blob endpoint, which reads the same folder.
 * @param {string} root
 * @returns {StorageDriver}
 */
function fsDriver(root) {
  /** @param {string} p */
  const full = (p) => path.join(root, ...checkPath(p).split("/"));
  /** @param {string} p */
  const metaFile = (p) => full(p) + ".meta.json";
  return {
    kind: "fs",
    async put(pathname, body, contentType) {
      const f = full(pathname);
      if (fs.existsSync(f)) throw new HttpError(409, "conflict", "That object already exists.");
      fs.mkdirSync(path.dirname(f), { recursive: true });
      fs.writeFileSync(f, body);
      fs.writeFileSync(metaFile(pathname), JSON.stringify({ contentType }));
    },
    async get(pathname) {
      const f = full(pathname);
      if (!fs.existsSync(f)) return null;
      const meta = fs.existsSync(metaFile(pathname)) ? JSON.parse(fs.readFileSync(metaFile(pathname), "utf8")) : {};
      return { stream: fs.createReadStream(f), contentType: meta.contentType || "application/octet-stream", size: fs.statSync(f).size };
    },
    async getBuffer(pathname) {
      const f = full(pathname);
      return fs.existsSync(f) ? fs.readFileSync(f) : null;
    },
    async del(pathnames) {
      for (const p of pathnames) {
        fs.rmSync(full(p), { force: true });
        fs.rmSync(metaFile(p), { force: true });
      }
    },
    async list(prefix) {
      checkPath(prefix);
      /** @type {string[]} */
      const out = [];
      /** @param {string} dir @param {string} rel */
      const walk = (dir, rel) => {
        if (!fs.existsSync(dir)) return;
        for (const name of fs.readdirSync(dir)) {
          const abs = path.join(dir, name);
          const r = rel ? rel + "/" + name : name;
          if (fs.statSync(abs).isDirectory()) walk(abs, r);
          else if (!name.endsWith(".meta.json") && r.startsWith(prefix)) out.push(r);
        }
      };
      walk(root, "");
      return out.sort();
    },
    async presignPut(pathname, opts) {
      const q = new URLSearchParams({ op: "put", path: checkPath(pathname), types: opts.contentTypes.join(","), max: String(opts.maxBytes), until: String(Date.now() + opts.ttlSeconds * 1000) });
      return "/__dev/blob?" + q.toString();
    },
    async presignGet(pathname, ttlSeconds) {
      const q = new URLSearchParams({ op: "get", path: checkPath(pathname), until: String(Date.now() + ttlSeconds * 1000) });
      return "/__dev/blob?" + q.toString();
    },
  };
}

/** @type {StorageDriver | null} */
let current = null;

/** @returns {StorageDriver} */
function storage() {
  if (current) return current;
  const env = process.env;
  if (env.BLOB_STORE_ID || env.BLOB_READ_WRITE_TOKEN) current = blobDriver();
  else if (isTest(env)) current = fsDriver(env.WVR_FS_STORAGE_DIR || path.join(os.tmpdir(), "wvroofing-test-storage"));
  else throw new HttpError(503, "not_configured", "Project storage isn't set up yet.");
  return current;
}

/** Test helper. */
function reset() {
  current = null;
}

module.exports = { configured, storage, reset, checkPath };
