/**
 * GENERATED by scripts/sync-cms-projects.mjs from content/projects/*.json
 * — do not edit by hand. Re-run the script (or just `npm run build`, which
 * runs it as "prebuild") after changing the content.
 *
 * These are the case studies Sean publishes himself through the admin portal at
 * /admin/ → Content → Projects. They are validated against the schema and
 * content rules in serverlib/cms.js at publish time AND again here at build
 * time, so the same rules that govern the hand-authored case studies in
 * projects.ts and projects-brief2.ts apply to these: genuine SC Design work
 * only, general area and never a street address, nothing invented, and a design
 * visualisation is never presented as a completed build.
 *
 * Images live in public/work/cms/<slug>/ and their width and height are measured
 * from the committed files, not taken on trust from the content.
 */
import type { Project } from "./projects";

export const cmsProjects: Project[] = [];
