/**
 * GENERATED by scripts/process-brief-images.mjs from scripts/brief-images.json
 * — do not edit by hand (re-run the script). Real project photos, drawings and
 * design visualisations from Sean's website brief (Sep 2026).
 *
 * kind: "photo" = real photograph of a completed/in-progress build,
 *       "drawing" = Sean's technical/planning drawing,
 *       "render" = design visualisation (never presented as a completed build).
 */
export type WorkImageKind = "photo" | "drawing" | "render";

export type WorkImage = {
  src: string;
  width: number;
  height: number;
  kind: WorkImageKind;
  alt: string;
  caption?: string;
};

export const workImages = {
  loftRearDormerBefore: { src: "/work/loft-rear-dormer/before.jpg", width: 320, height: 240, kind: "photo", alt: "Rear of a brick semi-detached house before its loft conversion" },
  loftRearDormerDrawing: { src: "/work/loft-rear-dormer/drawing.png", width: 731, height: 856, kind: "drawing", alt: "Proposed rear elevation drawing showing a full-width dormer with Juliet balconies" },
  loftDormerDrawing: { src: "/work/loft-dormer/drawing.png", width: 680, height: 826, kind: "drawing", alt: "Proposed rear elevation drawing of a dormer loft conversion" },
  loftDormerAfter: { src: "/work/loft-dormer/after.jpg", width: 796, height: 597, kind: "photo", alt: "Completed dormer loft conversion with dark grey cladding" },
  loftTileHung: { src: "/work/lofts/tile-hung-dormer.jpg", width: 870, height: 652, kind: "photo", alt: "Completed tile-hung dormer with oak-effect windows" },
  loftTimberClad: { src: "/work/lofts/timber-clad-dormer.jpg", width: 586, height: 782, kind: "photo", alt: "Completed timber-clad dormer on a brick house" },
  loftRear: { src: "/work/lofts/rear-loft-conversion.jpg", width: 748, height: 997, kind: "photo", alt: "Rear of a house with a completed loft conversion" },
  garage1BeforeInterior: { src: "/work/garage-conversion-1/before-interior.jpg", width: 469, height: 625, kind: "photo", alt: "Inside the garage before conversion" },
  garage1After: { src: "/work/garage-conversion-1/after.jpg", width: 460, height: 614, kind: "photo", alt: "Front of the house after the garage was converted, with a new window in place of the garage door" },
  garage1During: { src: "/work/garage-conversion-1/during.jpg", width: 497, height: 662, kind: "photo", alt: "The converted garage room during the works" },
  garage1AfterInterior: { src: "/work/garage-conversion-1/after-interior.jpg", width: 490, height: 653, kind: "photo", alt: "The finished room inside the converted garage" },
  garage2After: { src: "/work/garage-conversion-2/after.jpg", width: 320, height: 240, kind: "photo", alt: "The same frontage after the garage conversion, with a new window and extended porch canopy" },
  garage2Interior: { src: "/work/garage-conversion-2/interior.jpg", width: 736, height: 736, kind: "photo", alt: "Boot room with built-in timber seating and storage inside the converted garage" },
  extLanternDrawing: { src: "/work/extension-lantern/drawing.png", width: 752, height: 625, kind: "drawing", alt: "Proposed rear elevation drawing with a single-storey extension and roof lantern" },
  extLanternAfter: { src: "/work/extension-lantern/after.jpg", width: 320, height: 240, kind: "photo", alt: "Completed single-storey extension with a roof lantern and bi-fold doors" },
  extRearPebbledash: { src: "/work/extensions/rear-extension.jpg", width: 500, height: 500, kind: "photo", alt: "Completed single-storey rear extension with sliding doors on a semi-detached house" },
  extBeforeGarden: { src: "/work/extensions/before-rear.jpg", width: 701, height: 936, kind: "photo", alt: "Rear of a semi-detached house before an extension" },
  extCorner: { src: "/work/extensions/extension-corner.jpg", width: 677, height: 666, kind: "photo", alt: "Newly built rendered rear extension with French doors" },
  planningElevations: { src: "/work/planning/proposed-elevations.png", width: 1430, height: 1051, kind: "drawing", alt: "Coloured proposed elevations prepared for a householder planning application" },
  houseSectionsAB: { src: "/work/new-house/sections-a-b.png", width: 946, height: 698, kind: "drawing", alt: "Sections A and B through a new detached house" },
  houseSectionsCF: { src: "/work/new-house/sections-c-f.png", width: 1182, height: 800, kind: "drawing", alt: "Further sections through the new detached house" },
  houseRoofPlan: { src: "/work/new-house/roof-plan.png", width: 1247, height: 826, kind: "drawing", alt: "Roof plan of the new detached house" },
  houseRearSide: { src: "/work/new-house/rear-side-elevations.png", width: 806, height: 564, kind: "drawing", alt: "Rear and side elevations of the new detached house" },
  houseFloorPlan: { src: "/work/new-house/ground-floor-plan.png", width: 844, height: 510, kind: "drawing", alt: "Ground-floor plan of the new detached house with a double garage" },
  houseFrontSide: { src: "/work/new-house/front-side-elevations.png", width: 855, height: 596, kind: "drawing", alt: "Front and side elevations of the new detached house" },
  houseSketchViews: { src: "/work/new-house/3d-views.png", width: 857, height: 508, kind: "drawing", alt: "Three-dimensional line views of the new detached house" },
  vizBifold: { src: "/portfolio/viz-bifold-extension.jpg", width: 830, height: 554, kind: "render", alt: "Design visualisation of a rendered rear extension with bi-fold doors" },
  vizFlatRoofLantern: { src: "/portfolio/viz-flat-roof-extension.jpg", width: 797, height: 531, kind: "render", alt: "Design visualisation of a flat-roof extension with a roof lantern and corner glazing" },
  vizTimberClad: { src: "/portfolio/viz-timber-clad-extension.jpg", width: 731, height: 548, kind: "render", alt: "Design visualisation of a timber-clad garden extension with decking" },
  heroDuring: { src: "/portfolio/hero-during.jpg", width: 320, height: 240, kind: "photo", alt: "The rear extension during the build, before landscaping" },
  chapelRender: { src: "/portfolio/chapel-render.jpg", width: 467, height: 244, kind: "render", alt: "Design render of the chapel-to-gallery conversion" },
} satisfies Record<string, WorkImage>;

export type WorkImageId = keyof typeof workImages;

/** A work image with an optional caption override. */
export function wi(id: WorkImageId, caption?: string): WorkImage {
  return caption ? { ...workImages[id], caption } : workImages[id];
}

/** Human label for the image kind (shown on cards/galleries for non-photos). */
export const kindLabel: Record<WorkImageKind, string> = {
  photo: "Project photo",
  drawing: "Drawing",
  render: "Design visualisation",
};
