-- WV Roofing schema 0002 (A2): customer projects, uploads, photos and roof outlines.

-- One project per visualiser session. The customer holds a bearer token (only its
-- SHA-256 hash is stored). Deleted outright on request, or by the daily retention
-- run once expires_at passes (30 days unless an enquiry extends it).
CREATE TABLE IF NOT EXISTS wvr_projects (
  id uuid PRIMARY KEY,
  token_hash text NOT NULL,
  token_expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  photo_id uuid,
  mask_id uuid,
  selected_visual_id text,
  catalogue_version integer,
  consent_ai_at timestamptz,
  storage_notice_shown_at timestamptz,
  ip_hash text,
  ua_family text
);
CREATE INDEX IF NOT EXISTS wvr_projects_expires_idx ON wvr_projects (expires_at);

-- Every presigned upload the server hands out. The path is generated by the server;
-- a commit accepts only an unconsumed, unexpired upload belonging to its own project.
CREATE TABLE IF NOT EXISTS wvr_uploads (
  id uuid PRIMARY KEY,
  project_id uuid NOT NULL REFERENCES wvr_projects (id) ON DELETE CASCADE,
  kind text NOT NULL,
  pathname text NOT NULL UNIQUE,
  content_type text NOT NULL,
  max_bytes integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz
);
CREATE INDEX IF NOT EXISTS wvr_uploads_pending_idx ON wvr_uploads (created_at) WHERE consumed_at IS NULL;

-- Photos are immutable: a new photo is a new row. original_path holds the customer's
-- file with its metadata removed losslessly (pixel data untouched); working_path holds
-- the normalised lossless PNG (oriented, at most 1600 px on the long edge) that the
-- roof outline, renders and composites use.
CREATE TABLE IF NOT EXISTS wvr_photos (
  id uuid PRIMARY KEY,
  project_id uuid NOT NULL REFERENCES wvr_projects (id) ON DELETE CASCADE,
  original_path text NOT NULL,
  original_sha256 text NOT NULL,
  original_mime text NOT NULL,
  original_bytes integer NOT NULL,
  orig_w integer NOT NULL,
  orig_h integer NOT NULL,
  exif_orientation smallint NOT NULL DEFAULT 1,
  working_path text NOT NULL,
  work_w integer NOT NULL,
  work_h integer NOT NULL,
  original_is_client_resized boolean NOT NULL DEFAULT false,
  quality jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Roof outlines. png: alpha 0 marks the roof (the same convention as OpenAI's edit
-- masks), at the working copy's exact size. editor_meta keeps the editable shapes.
CREATE TABLE IF NOT EXISTS wvr_masks (
  id uuid PRIMARY KEY,
  project_id uuid NOT NULL REFERENCES wvr_projects (id) ON DELETE CASCADE,
  photo_id uuid NOT NULL REFERENCES wvr_photos (id) ON DELETE CASCADE,
  png bytea NOT NULL,
  w integer NOT NULL,
  h integer NOT NULL,
  coverage real NOT NULL,
  editor_meta jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
